name: cypress-layout-inspector tests

on:
    push:
        branches:
            - 'master'
    pull_request:

jobs:
    cypress-run:
        runs-on: ubuntu-16.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress.io
              uses: cypress-io/github-action@v1.16.1
              with:
                  build: npm run build
